### PR TITLE
update doc and collate

### PR DESCRIPTION
**Pull request by yanji1221**
update doc and collate

### CODE REVIEW

**Comment by yanji1221** [comment]
Sorry Erik I realise that there are some problem with my collates. Can you collate again? Thank you! I promise this would be the last! @erik0704

**Comment by erik0704** [comment]
The ug & dg isnt affected by this pr right ?

**Comment by yanji1221** [comment]
yes. I only updated the portfolio page

**Comment by erik0704** [comment]
Remember to make & upload your portfolio I've uploaded the team submissions.

**Pull request merged**
